baseURL = "http://localhost/"
languageCode = "en-us"
title = "LinuxBoot"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsUseClassic = true

# for the calendar iframe, we need raw HTML, which is omitted since Hugo 0.60.0
# unless `unsafe = true` is set. See https://gohugo.io/news/0.60.0-relnotes/
[markup.goldmark.renderer]
  unsafe = true

[Params]
  useChroma = true
	subtitle = "Let Linux do it"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"
	dateFormat = "January 2, 2006"
	commit = false
	rss = false
	comments = true
	readingTime = true

[Params.Author]
	name = "The LinuxBoot project"
	website = "https://www.linuxboot.org"
	email = "linuxboot@googlegroups.com"
	github = "linuxboot"
	twitter = "LinuxBootOrg"

[[menu.main]]
	name = "FAQ"
	url = "page/faq/"
	weight = 1

[[menu.main]]
	name = "Artwork"
	url = "page/artwork/"
	weight = 2
